repos:
#-   repo: git://github.com/pre-commit/pre-commit-hooks
#    rev: v3.2.0
#    hooks:
#    -   id: trailing-whitespace
#    -   id: end-of-file-fixer
#    -   id: check-yaml
#    -   id: check-added-large-files
#
#-   repo: git://github.com/pycqa/pylint
#    rev: pylint-2.6.0
#    hooks:
#    -   id: pylint
#        args: ["--fail-under=8"]

-   repo: local
    hooks:
    -   id: commit-msg-regex-hook
        name: commit-msg-regex-hook
        entry: commit-msg-regex-hook
        language: python
        args: ["--pattern='Signed-off-by: .* <(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|'(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21\\x23-\\x5b\\x5d-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])*')@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\\[(?:(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9]))\\.){3}(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9])|[a-z0-9-]*[a-z0-9]:(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21-\\x5a\\x53-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])+)\\])>'",
                "--debug"]
        #args: ["--pattern='[A-Z]{3,4}-[0-9]{3,6} \\| [\\w\\s]* \\| .+'",
        #        "--debug"]
        stages: [commit-msg]

